# Generated by Django 5.2.7 on 2025-10-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('terminal', '0003_alter_terminalqueue_waiting_time_entrylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='queue_entry',
        ),
        migrations.AddField(
            model_name='trip',
            name='entry_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='terminal.entrylog'),
        ),
    ]
