# Generated by Django 5.2.4 on 2025-10-30 00:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_rename_queue_terminalqueue'),
        ('vehicles', '0002_vehicle_cr_number_vehicle_or_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalqueue',
            name='waiting_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('insufficient', 'Insufficient Balance'), ('invalid', 'Invalid QR')], default='failed', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_actions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Entry Log',
                'verbose_name_plural': 'Entry Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
