# Generated by Django 5.2.7 on 2025-10-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_trip_queue_entry_trip_entry_log'),
        ('terminal', '0003_alter_terminalqueue_waiting_time_entrylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminalQueue',
        ),
    ]
