# Generated by Django 5.2.4 on 2025-11-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
