# Generated by Django 5.2.4 on 2025-11-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_alter_systemsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='departed_at',
            field=models.DateTimeField(blank=True, help_text='Time the vehicle exited the terminal.', null=True),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if vehicle is still in terminal queue.'),
        ),
    ]
