# Generated by Django 5.2.4 on 2025-11-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_entrylog_departed_at_entrylog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='entry_cooldown_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
