# Generated by Django 5.0.7 on 2026-01-11 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_systemsettings_bus_max_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalfeebalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
