# Generated by Django 5.0.7 on 2026-01-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_terminal_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalactivity',
            options={'ordering': ['-timestamp']},
        ),
    ]
