# Generated by Django 5.0.7 on 2026-01-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0015_alter_terminalactivity_options'),
        ('vehicles', '0017_add_transaction_and_queue_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='countdown_duration_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Duration of countdown timer before state transitions (in seconds)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='queue_refresh_interval_seconds',
            field=models.PositiveIntegerField(default=15, help_text='How often queue displays auto-refresh (in seconds)'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(default='—', max_length=50)),
                ('driver_name', models.CharField(default='N/A', max_length=200)),
                ('route_name', models.CharField(default='Unassigned', max_length=200)),
                ('entry_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wallet_balance_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_date', models.DateField()),
                ('transaction_year', models.PositiveIntegerField()),
                ('transaction_month', models.PositiveIntegerField()),
                ('transaction_day', models.PositiveIntegerField()),
                ('is_revenue_counted', models.BooleanField(default=True, help_text='Whether this transaction counts toward daily revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='vehicles.driver')),
                ('entry_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='terminal.entrylog')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-entry_timestamp'],
                'indexes': [models.Index(fields=['transaction_date'], name='terminal_tr_transac_0c20a8_idx'), models.Index(fields=['transaction_year', 'transaction_month'], name='terminal_tr_transac_a62bce_idx'), models.Index(fields=['vehicle_plate'], name='terminal_tr_vehicle_cad053_idx')],
            },
        ),
    ]
