# Generated by Django 5.2.4 on 2025-10-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_type', models.CharField(blank=True, max_length=20, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='licenses/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(default='Unnamed Vehicle', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('jeepney', 'Jeepney'), ('bus', 'Bus'), ('van', 'Van'), ('tricycle', 'Tricycle'), ('taxi', 'Taxi')], max_length=50)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('private', 'Private')], default='owned', max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('manual', 'Manual Payment (In-Station)'), ('online', 'Online Payment'), ('bank_transfer', 'Bank Transfer'), ('gcash', 'GCash'), ('maya', 'Maya')], default='manual', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='vehicles.wallet')),
            ],
        ),
    ]
