# Generated by Django 5.2.4 on 2025-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cr_number',
            field=models.CharField(default='TEMP-CR', max_length=50, unique=True, verbose_name='Certificate of Registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='or_number',
            field=models.CharField(default='TEMP-OR', max_length=50, unique=True, verbose_name='Official Receipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(default='TEMP-VIN', max_length=50, unique=True, verbose_name='Vehicle Identification Number (VIN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year_model',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
