# Generated by Django 5.2.4 on 2025-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_cr_number_vehicle_or_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_value',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
