# Generated by Django 5.0.7 on 2025-11-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_departure_time_vehicle_last_enter_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='status',
            new_name='status_temp',
        ),
    ]
