# Generated by Django 5.0.7 on 2025-11-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_rename_status_vehicle_status_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='status_temp',
            new_name='status',
        ),
    ]
