# Generated by Django 5.0.7 on 2026-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_route_options_remove_driver_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(upload_to='drivers/photos/', max_length=255, verbose_name='driver_photo'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(default='professional', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='vehicles/qrcodes/', verbose_name='qr_code'),
        ),
    ]
