# Generated by Django 5.0.7 on 2026-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_vehicle_cr_number_alter_vehicle_or_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(upload_to='drivers/photos/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/qrcodes/'),
        ),
    ]
