# Generated by Django 5.0.7 on 2026-01-12 14:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_driver_driver_photo_alter_vehicle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
