# Generated by Django 5.0.7 on 2026-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_driver_license_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(upload_to='drivers/photos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/qrcodes'),
        ),
    ]
