# Generated by Django 5.0.7 on 2026-01-13 02:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_queuehistory_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driver_photos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vehicle_qrcodes'),
        ),
    ]
